### ISSUE TITLE
Find a way to distribute binaries w/ versioning (Homebrew?)

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/SwiftGen#1]
Distributing the binaries via Homebrew maybe? Or is there a better distribution system that would fit distributing swift tools? (e.g. `gem` being more focused on ruby tools)

**Comment by AliSoftware** [comment]
We should also add a CHANGELOG (where @esttorhe could credit himself for #8)

**Comment by esttorhe** [comment]
If you want to include a `CHANGELOG` I've used [this one](https://github.com/skywinder/github-changelog-generator) and I'm liking it so far.

I suggested it on https://github.com/czechboy0/XcodeServerSDK framework; you can check it out there

**Comment by AliSoftware** [comment]
Use a script to automate generation of a file… on that repo containing scripts to automate generation of files… automation-sception, I like it :D

**Comment by esttorhe** [comment]
«Scripts»ception
![](http://media.giphy.com/media/yXCye58cRyxy0/giphy.gif)

**Comment by AliSoftware** [comment]
PR pending: https://github.com/Homebrew/homebrew/pull/42983

**Comment by AliSoftware** [comment]
Seems like it's gonna have to wait for Xcode 7 to be out of beta :unamused:

**Comment by esttorhe** [comment]
hahaha; that kind of makes sense though.

I still think there should be a better way to distribute other than HB

Mostly because there's no way to guarantee which `Swift` version is running on the installing machine

**Comment by AliSoftware** [comment]
Yeah maybe I should pre-package my binaries in a tarball and post them in Homebrew/homebrew-binary instead.

If you have a better solution or suggestion for another distribution system I'd be happy to hear!

**Comment by AliSoftware** [comment]
SwiftGen is now available via Homebrew!

**Comment by esttorhe** [comment]
```console
==> Downloading https://homebrew.bintray.com/bottles/swiftgen-0.4.4.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring swiftgen-0.4.4.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/swiftgen/0.4.4: 19 files, 15M
```

:tada:

**Comment by AliSoftware** [comment]
:beers:

**Comment by iGranDav** [comment]
:beers: nice @AliSoftware :)
