### ISSUE TITLE
Homebrew install is broken if not rebuilt from source with Xcode 7.3

### ISSUE THREAD

**Issue by ChristopherRogers** [AliSoftware/SwiftGen#104]
You will get an error saying that a symbol expected from PathKit to be found in libswiftcore.dylib could not. I assume this is because the pre-build binaries are building against Swift 2.1.1. With Xcode 7.3/Swift 2.2, this symbol (SequenceBox something or another, sorry I don't have the log anymore.) no longer exists.

**Comment by AliSoftware** [comment]
Thanks for letting me know.

An interesting question to ask @kylef is to know if PathKit needs any migration to Swift 2.2 (does it compile with Xcode 7.3 alright?) before regenerating a new version for SwiftGen.

In the meantime I might suggest to install either via the Rakefile or check of homebrew has some `--no-bottle` flag or similar to force it to rebuild until we find a more suitable solution.

**Comment by kylef** [comment]
> An interesting question to ask @kylef is to know if PathKit needs any migration to Swift 2.2 (does it compile with Xcode 7.3 alright?) before regenerating a new version for SwiftGen.

Swift 2.2 is a patch release and **should** not contain breaking changes, I would not expect PathKit to break.

**Comment by ChristopherRogers** [comment]
It does. I've been using `--build-from-source` for now.

**Comment by AliSoftware** [comment]
> Swift 2.2 is a minor release and should not contain breaking changes, I would not expect PathKit to break.

@kylef Yeah I agree, but then I don't understand why the homebrew pre-build bottles of SwiftGen should break, as the ZIP file I bundle in Homebrew contains the swiftgen binary but also all its dependent frameworks, including Stencil, Commander, PathKit… and the Swift dylibs it has been built with.

So I'm not sure to understand how this could break SwiftGen as it doesn't rely on the locally installed Xcode version and has all its dependencies copied along with the binary… any idea about that?

**Comment by ChristopherRogers** [comment]
Perhaps because I'm running it inside of a Swift "script" environment (from a build script in Xcode) it's messing with the version of Swift it's using and not a general issue with using it, say, on the command line.

**Comment by AliSoftware** [comment]
@ChristopherRogers Mmmh maybe but I would be surprised if it did.

Could you run `otool -L swiftgen` in your Script Build Phase and see what is printed in the Build Log output? Thanks!

Also, how do you refer to `swiftgen` in your Script Build Phase? Simply using `swiftgen`? Or using its full path `/usr/bin/swiftgen`? Anything else?

**Comment by ChristopherRogers** [comment]
I'll have to get back to you later on that (when I can check it at work).

**Comment by ChristopherRogers** [comment]
It seems to work fine when run standalone, directly from a build script in Xcode, and even from the REPL. It's just that I can't run it from inside a Swift script, so I guess this is a limitation of Swift itself.

Here's the otool output by the way.

```
/usr/local/bin/swiftgen:
	@rpath/PathKit.framework/Versions/A/PathKit (compatibility version 1.0.0, current version 1.0.0)
	@rpath/Stencil.framework/Versions/A/Stencil (compatibility version 1.0.0, current version 1.0.0)
	@rpath/Commander.framework/Versions/A/Commander (compatibility version 1.0.0, current version 1.0.0)
	@rpath/GenumKit.framework/Versions/A/GenumKit (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1256.1.0)
	@rpath/libswiftAppKit.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftCore.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftCoreData.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftCoreImage.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftDarwin.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftDispatch.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftFoundation.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libswiftObjectiveC.dylib (compatibility version 0.0.0, current version 0.0.0)
```

After reinstalling from source, the versions for the Swift libraries change (as expected).

```
/usr/local/bin/swiftgen:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1258.1.0)
	@rpath/PathKit.framework/Versions/A/PathKit (compatibility version 1.0.0, current version 1.0.0)
	@rpath/Stencil.framework/Versions/A/Stencil (compatibility version 1.0.0, current version 1.0.0)
	@rpath/Commander.framework/Versions/A/Commander (compatibility version 1.0.0, current version 1.0.0)
	@rpath/GenumKit.framework/Versions/A/GenumKit (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1258.0.0)
	@rpath/libswiftAppKit.dylib (compatibility version 1.0.0, current version 703.0.18)
	@rpath/libswiftCore.dylib (compatibility version 1.0.0, current version 703.0.18)
	@rpath/libswiftCoreData.dylib (compatibility version 1.0.0, current version 703.0.18)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 703.0.18)
	@rpath/libswiftCoreImage.dylib (compatibility version 1.0.0, current version 703.0.18)
	@rpath/libswiftDarwin.dylib (compatibility version 1.0.0, current version 703.0.18)
	@rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 703.0.18)
	@rpath/libswiftFoundation.dylib (compatibility version 1.0.0, current version 703.0.18)
	@rpath/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 703.0.18)
```

And here is the actual error:

```
dyld: Symbol not found: __TMPdCSs12_SequenceBox
  Referenced from: /usr/local/Cellar/swiftgen/0.8.0/bin/../lib/PathKit.framework/Versions/A/PathKit
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/Cellar/swiftgen/0.8.0/bin/../lib/PathKit.framework/Versions/A/PathKit
```

**Comment by AliSoftware** [comment]
Thanks for the follow-up!

> It's just that I can't run it from inside a Swift script, so I guess this is a limitation of Swift itself.

Ha that makes much more sense indeed. If you use any Swift library, which depends on the Swift runtime libraries themselves, you'll have to use the same Swift runtime version for everything.
Using SwiftGen in a Swift script means your Swift script itself will use the system-installed Swift (2.2) while depending on a library (PathKit) which was built with 2.1 (from the homebrew bottle) hence the issue :wink:

So to run everything with the same version you can either rebuild everything from source as you did (probably the best way) or maybe you might have been able to use `xcrun` to make your own Swift script run using the 2.1 runtime (not worth it IMHO), as long as everything uses the same runtime.
