### ISSUE TITLE
Can't run script from build phases

### ISSUE THREAD

**Issue by sashakid** [AliSoftware/SwiftGen#106]
Hi, I'm not specialist in bash and can't run swiftgen script:

1) I've installed swiftgen with cocoapods
2) Then I pasted the following script in build phase:
```
if which swiftgen >/dev/null; then
  swiftgen storyboards "$PROJECT_DIR/my_project_name" --output "$PROJECT_DIR/Constants/Storyboards.swift"
  swiftgen images "$PROJECT_DIR/my_project_name" --output "$PROJECT_DIR/Constants/Images.swift"
else
  echo "warning: SwiftGen not installed, download it from https://github.com/AliSoftware/SwiftGen"
fi
```
3) I received error:`warning: SwiftGen not installed, download it from https://github.com/AliSoftware/SwiftGen`

As I understand, I should add somewhere root path to swiftgen `$PODS_ROOT/SwiftGen/bin/swiftgen `?

Could you help me, please, what am I doing worng? See my screenshots to get the full picture:
[pic1](https://monosnap.com/file/uhoLEsLzk7OGiaNGCZapW38ahDo6uC)
[pic2](https://monosnap.com/file/CAI6J60wv6HuppNuRoQziobWGW7XrZ)
[pic3](https://monosnap.com/file/tI5lm2Hxp2WHRJkb9hwlEaCSRfLRyE)

**Comment by AliSoftware** [comment]
> As I understand, I should add somewhere root path to swiftgen `$PODS_ROOT/SwiftGen/bin/swiftgen`?

 That's exactly it.

**Comment by sashakid** [comment]
@AliSoftware where is the place, please?

**Comment by AliSoftware** [comment]
Instead of `swiftgen` whwn invoking each command,  so that it knows where to find the binary .

**Comment by sashakid** [comment]
if which swiftgen >/dev/null; then
"$PODS_ROOT/SwiftGen/bin/swiftgen" storyboards "$PROJECT_DIR/airportla" --output "$PROJECT_DIR/Constants/Storyboards.swift"
"$PODS_ROOT/SwiftGen/bin/swiftgen" images "$PROJECT_DIR/airportla" --output "$PROJECT_DIR/Constants/Images.swift"
else
echo "warning: SwiftGen not installed, download it from https://github.com/AliSoftware/SwiftGen"
fi

**Comment by AliSoftware** [comment]
You should probably remove the `if which` too (and the `else` and `fi`) to only keep the invocation lines. The purpose of that `if which swiftgen` test in s to check if the binary named `swftgen` is installed system-wide and warn if it isn't installed but in the context in f a CocoaPods installation by design it's not installed system-wide but local to your project so that test is useless.

**Comment by sashakid** [comment]
Thanks a lot! It works :+1:

**Comment by AliSoftware** [comment]
Next time please ask those kind of help on StackOverflow, the GitHub issue tracker is for actual bugs in SwiftGen, not for a helpdesk :wink:
