### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by AndrewSB** [AliSoftware/SwiftGen#116]
Whats the timeline for this library to support Swift 3?
Thoughts on adding a `--swift3` flag to the commands to generate Swift 3 compatible code?

**Comment by AliSoftware** [comment]
There is no need for a `--swift3` support as templates already provides this ability and you can already customize the generated code and generate whatever code you want.

For example for colors create a `colors-swift3.stencil` template and use `swiftgen colors -t swift3` and it will work.

See the documentation about creating your custom templates in the README and in the doc/ folder.

I'm closing this issue as I don't plan to bundle Swift 3 templates with SwiftGen until Swift 3 itself is stable and the syntax for Swift 3 is frozen, but will do it late '16 at the same time Swift 3 is officially frozen and out.

But feel free to make a PR I  the meantime to share your `xxx-swift3.stencil` templates if you create ones for your own use case and I'll gladly include them with the other templates already provided with SwiftGen (see the templates/ directory in the repo)

**Comment by AndrewSB** [comment]
in the process of making a PR, you're right there aren't many (if any) changes required for swiftgen, moreso changes in the dependencies that need to be integrated.

Thank you for explaining how to make the template, hoping to have that to you later today 😄

**Comment by AliSoftware** [comment]
:+1:

**Comment by AliSoftware** [comment]
@AndrewSB as @akaralar pointed out in https://github.com/AliSoftware/SwiftGen/pull/124#issuecomment-223342448 we might want to consider doing another PR to slightly adapt the Swift 3 templates you submitted, and make `enum cases` *lowercase*, as it will be the new Swift 3 conventions!

**Comment by Sajjon** [comment]
Hi! Thanks @AliSoftware  for amazing SwiftGen! Best thing that happened Swift since... the release of Swift! 👍  

I have recently converted my whole project - which heavily makes use of SwiftGen - to Swift 3.

No I get compilation error 

> CVarArgType has been renamed CVarArg
For the method 

```
private static func tr(key: String, _ args: CVarArgType...) -> String {
    let format = NSLocalizedString(key, comment: "")
    return String(format: format, locale: NSLocale.currentLocale(), arguments: args)
  }
```

And I also think we should change `key: String` to `_ key: String` for both the method above and this below:
```
func tr(key: L10n) -> String {
  return key.string
}
```

@AndrewSB did you get it working with Swift 3?

**Comment by AliSoftware** [comment]
@Sajjon I'm not sure I understand how you have `private static func tr(key: String, _ args: CVarArgType...) -> String` while the Swift 3 template bundled with SwiftGen uses `CVarArg` [here](https://github.com/AliSoftware/SwiftGen/blob/master/templates/strings-swift3.stencil#L33)?

**Comment by Sajjon** [comment]
@AliSoftware thx for quick reply, maybe something wrong with xcode -select? I am using Xcode 8, beta 6 and swiftgen 2.

```
xcode-select --version
xcode-select version 2343.
```

**Comment by Sajjon** [comment]
Maybe I should try running swiftgen from terminal first....

**Comment by AliSoftware** [comment]
And are you sure you're using the `-t swift3` template when invoking `swiftgen strings -t swift3`?

**Comment by Sajjon** [comment]
@AliSoftware no I am not, so that must be it then! 👍 where did I miss this instruction? It was not part of the README? Maybe we can add a section rather high up in the README mentioning this? 😄

**Comment by AliSoftware** [comment]
Indeed it wasn't explicitly stated in the README (but only in the CHANGELOG when that template was added to SwiftGen).

Might indeed be a good idea to add a section in the README to insist about available templates, including the Swift 3 one, but also the new dot-structured one.

**Comment by Sajjon** [comment]
@AliSoftware Also it would be good if the SwiftGen Strings template - `strings-swift3.stencil` (right?) could be updated to make use of the latest Swift 3 syntax. The enums should be lowercased.

Also maybe the function `func tr` should have `_ key: String` as argument instead of `key: String`, what do you think?

I am not sure I understand the syntax in said file though, probably the function `snakeToCamelCase` should be changed to make use of leading lower case character?

**Comment by AliSoftware** [comment]
I just added a mention in the README, will push that commit soon.
Good point about the lowercased enums for Swift 3. Will change that in an upcoming PR.

About `tr(key: L10n)`, as stated above it's [used properly here](https://github.com/AliSoftware/SwiftGen/blob/master/templates/strings-swift3.stencil#L27) in the `string-swift3.stencil` template by calling it via `tr(key: "…")` mentioning the first parameter at call site, so we're already good on that front.

**Comment by Sajjon** [comment]
Sweet, the `-t swift3` flag worked, however it still doesn't compile, still the same method:
```
  private static func tr(key: String, _ args: CVarArg...) -> String {
    let format = NSLocalizedString(key, comment: "")
    return String(format: format, locale: NSLocale.current(), arguments: args)
  }
```

It is strange that SwiftGen generates this code, is it not? Because while looking at the `string-swift3.stencil` file, this is what it contains.

```
  private static func tr(key: String, _ args: CVarArg...) -> String {
    let format = NSLocalizedString(key, comment: "")
    return String(format: format, locale: Locale.current, arguments: args)
  }
```

See the difference?  `NSLocale.current()` vs `NSLocale.current()`. How come I get the latter? What am I doing wrong now? I have installed SwiftGen via brew:
```
› swiftgen --version
SwiftGen v2.0.0
```

and running
```
swiftgen strings -t swift3 --output Some/Path/To/Output
```

What am I missing? Now I am using Xcode 7 as `xcode-select`, 
```
sudo xcode-select -switch /Applications/Xcode.app 
xcode-select --version     
xcode-select version 2343.
```

But I have also tried:
```
sudo xcode-select -switch /Applications/Xcode-beta.app
```

With the same result.

*THANKS A BUNCH!*

**Comment by AliSoftware** [comment]
That's because #150 which fixed that is only in `master` and was not part of `2.0.0` so it's not released yet.

I was actually in the process of doing a release when your comment came out so I'll first lowercase all enums before releasing the next version, hopefully today.

**Comment by Sajjon** [comment]
@AliSoftware you sir, you rock! 😍

**Comment by AliSoftware** [comment]
@Sajjon just pushed that PR, would love if you could test it with your project (by compiling `master` as per the README instructions then generate code for everything using `-t swift3` to check the generated code compiles and is valid Swift 3)

**Comment by Sajjon** [comment]
@AliSoftware I am on it! Will let you know ASAP!

**Comment by Sajjon** [comment]
Compilation using `rake install` I presume? I performed a `brew uninstall --force swiftgen` prior to this. Cloned master branch, cd Swiftgen and in repo root `rake install`, results in error:

rake install                                     

== Building PathKit.framework ==

set -o pipefail && xcodebuild -project Pods/Pods.xcodeproj -target PathKit -configuration Release | xcpretty -c
2016-09-04 14:56:17.104 xcodebuild[10175:250694] CoreSimulator is attempting to unload a stale CoreSimulatorService job.  Detected Xcode.app relocation or CoreSimulatorService version change.  Framework path (/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework) and version (209.19) does not match existing job path (/Applications/Xcode-beta.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService) and version (303.7).
▸ Building Pods/PathKit [Release]
▸ Check Dependencies
2016-09-04 14:56:17.358 xcodebuild[10175:250694] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
2016-09-04 14:56:17.376 xcodebuild[10175:250694] *** Assertion failure in -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreSimulator/CoreSimulator-209.19/CoreSimulator/SimServiceContext.m:536
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: The loaded com.apple.CoreSimulator.CoreSimulatorService job does not match our expectations: pathOfLoadedJob: /Applications/Xcode-beta.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService, our frameworkPath: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework
Stack:
▸ Processing Info.plist
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   +[NSException raise:format:arguments:] (in CoreFoundation)
  3   -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] (in Foundation)
  4   -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid] (in CoreSimulator)
  5   -[SimServiceContext connect] (in CoreSimulator)
  6   -[SimServiceContext initWithDeveloperDir:connectionType:] (in CoreSimulator)
  7   __63+[SimServiceContext sharedServiceContextForDeveloperDir:error:]_block_invoke_2 (in CoreSimulator)
  8   _dispatch_client_callout (in libdispatch.dylib)
  9   _dispatch_barrier_sync_f_invoke (in libdispatch.dylib)
 10   +[SimServiceContext sharedServiceContextForDeveloperDir:error:] (in CoreSimulator)
 11   __60+[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:]_block_invoke (in DVTiPhoneSimulatorRemoteClient)
 12   _dispatch_client_callout (in libdispatch.dylib)
 13   dispatch_once_f (in libdispatch.dylib)
 14   +[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:] (in DVTiPhoneSimulatorRemoteClient)
 15   __42-[DVTiPhoneSimulatorLocator startLocating]_block_invoke (in IDEiOSSupportCore)
 16   __DVTDispatchAsync_block_invoke (in DVTFoundation)
 17   _dispatch_call_block_and_release (in libdispatch.dylib)
 18   _dispatch_client_callout (in libdispatch.dylib)
 19   _dispatch_root_queue_drain (in libdispatch.dylib)
 20   _dispatch_worker_thread3 (in libdispatch.dylib)
 21   _pthread_wqthread (in libsystem_pthread.dylib)
 22   start_wqthread (in libsystem_pthread.dylib)

sh: line 1: 10175 Abort trap: 6           xcodebuild -project Pods/Pods.xcodeproj -target PathKit -configuration Release
     10176 Done                    | xcpretty -c
rake aborted!
Command failed with status (134): [set -o pipefail && xcodebuild -project Pod...]
/Users/alge/Developer/iOS/SwiftGen/Rakefile:24:in `xcpretty'
/Users/alge/Developer/iOS/SwiftGen/Rakefile:72:in `block (3 levels) in <top (required)>'
Tasks: TOP => install => install:light => build => dependencies:PathKit
(See full trace by running task with --trace)

**Comment by AliSoftware** [comment]
Will look into it. Please continue this conversation in #166 to avoid spamming others following this one 😉

**Comment by Sajjon** [comment]
@AliSoftware from error above, do I need to install anything else before? Seams like `PathKit` is missing?
