### ISSUE TITLE
Cocoapods and Templates

### ISSUE THREAD

**Issue by AFcgi** [AliSoftware/SwiftGen#120]
It is possible to integrate a own template with cocoa pods integration of Swiftgen? When I use Swiftgen via brew installation then it's possible to integrate owned templates. But when I would use via Cocoapods, Swiftgen can't find my template.

**Comment by AliSoftware** [comment]
What is the command you're using in your build phase especially the path to your templates?

**Comment by AliSoftware** [comment]
Ping @AFcgi ?

**Comment by AFcgi** [comment]
Sorry for my late reply. I use the --template option to integrate my template from <code>~/Library/Application Support/SwiftGen/templates</code> path. The same path doesn't work with the cocoa pods integration.

**Comment by AFcgi** [comment]
I solved the problem.

**Comment by AliSoftware** [comment]
Cool! Care to share the solution in case anyone have a similar issue? Thx!

**Comment by AFcgi** [comment]
I try <code>--templatePath "$PROJECT_DIR/xxx.stencil"</code> and it works fine.
