### ISSUE TITLE
Font support in Homebrew version?

### ISSUE THREAD

**Issue by akaralar** [AliSoftware/SwiftGen#121]
I installed `swiftgen` through `brew` but when I run `swiftgen fonts .` it outputs `Unknown command: 'fonts'`. Also when I type `swiftgen --help` it doesn't list the `fonts` command. I believe the current version of master has this feature, when will it be released on `brew`?

**Comment by AliSoftware** [comment]
I was on a work trip for two days hence the delay, but I plan to make the release tonite actually just just wait for a few hours.
