### ISSUE TITLE
Generating Colors from txt files will stop generation on comments and blank lines

### ISSUE THREAD

**Issue by dostrander** [AliSoftware/SwiftGen#140]
If you have comments (lines starting with `#` ) within your Colors.txt file it will bail when it hits those comments.

**Comment by AndrewSB** [comment]
Colors.txt also no longer supports blank lines. It silently fails and doesn't output all colors after the first newline in the file

**Comment by dostrander** [comment]
@AndrewSB When was that introduced and what is the reasoning behind the decision?

**Comment by AndrewSB** [comment]
@dostrander I am unsure, but recently (yesterday) when I ran Swiftgen I got a bunch of compile errors saying my color enum cases weren't defined, I removed all the blank lines I'd had in the file and it was fixed.

My colors.txt has had those blank lines for a better part of 6 months now.

This may have something to do with Updating to the beta Mac OS, but I'm not sure and have no idea why it would - the two events just seem correlated.

More probably it has something to do with the changes to color.txt parsing in release 1.0.0 or 1.1.0

**Comment by AndrewSB** [comment]
Can we edit the title of this issue to end with "comments or blank lines"?

**Comment by dostrander** [comment]
@AndrewSB Just verified this is a problem. 

The fix I did in PR #141 will also fix the blank lines

**Comment by AndrewSB** [comment]
Looks great, this issue looks closable pending the PR merge
