### ISSUE TITLE
Generated enums are (inconsistently) jumping to the wrong enum when calling `string`

### ISSUE THREAD

**Issue by dostrander** [AliSoftware/SwiftGen#142]
When building and running projects you will see your string and/or color enums getting "confused" and jumping to the wrong enum value in the switch statement. This happens very inconsistently and a clean + build will do the trick in fixing this issue, however it's very annoying and I'm not sure where it is coming from and wanted to bring it up.

~~Possible relevant twitter thread:~~
~~https://twitter.com/jckarter/status/744657583043010560~~

**Edit** - strikethrough the twitter thread because it's probably not applicable

**Comment by AliSoftware** [comment]
I don't think that's linked with the issue evoked within the twitter thread. Looks more like a mis-recompilation to me, somehow. Definitely seems like a compiler bug anyway.

**Comment by dostrander** [comment]
Yeah that'd make the most sense to me as well

**Comment by AliSoftware** [comment]
I'm actually wondering if I should keep this issue open, as I won't be able to do anything about it on the SwiftGen level, it being an Xcode bug in the general level (I'm guessing it could even happen in your own manually-written code then?).

**Comment by dostrander** [comment]
Yeah that's reasonable
