### ISSUE TITLE
Failing to compile on tvOS

### ISSUE THREAD

**Issue by Megatron1000** [AliSoftware/SwiftGen#143]
This is due to the lines:

#if os(iOS)
  import UIKit.UIImage
  typealias Image = UIImage
#elseif os(OSX)
  import AppKit.NSImage
  typealias Image = NSImage
#endif

which does not include a case for tvOS

**Comment by AliSoftware** [comment]
\cc @tbaranes who did add those for OS X support, maybe they can quickly fix this?

The fix should be easy enough (a quick PR would be welcome!).

In the meantime, simply customize the template for your use case (that's the beauty of SwiftGen, as you can provide your own templates to fit your needs if you dot like or have issues with the bundled ones :wink:)

**Comment by AliSoftware** [comment]
Of course the fix should also include `|| os(watchOS)` in the test condition I guess, in addition to `|| os(tvOS)`?

**Comment by tbaranes** [comment]
I don't have any projects on tvOS or watchOS to test it, but as you said, I think we can reuse the same templates at least for colors, fonts, localizables (this one should already be working for all the platforms) by just adding `|| os(tvOS)`. Storyboard may needs a custom one if they can be different from iOS.

That should be an easy fix 🤔

**Comment by Megatron1000** [comment]
I was using it for storyboards and images on tvOS without any problems, up until this new #if was added. TV storyboards seem to be pretty much identical to iOS ones, apart from the meta tag at the top of the storyboard file identifying it as being for TV.

**Comment by jhihguan** [comment]
did this release? I use homebrew and `brew update; brew upgrade` right now, it doesn't have `|| os(tvOS) || os(watchOS)`

**Comment by AliSoftware** [comment]
@jhihguan not yet, indeed. Will try to make a release tonight or tomorrow.

**Comment by AliSoftware** [comment]
Or you could use a custom template in the meantime, after all that's the force of SwiftGen and the release will only fix the bundled templates in case you don't use a custom one… :wink:

**Comment by AliSoftware** [comment]
Just released version 2.0.0 including these changes in CocoaPods.
Submitted to Homebrew too (but just have to wait someone from the Homebrew team merge it in couple of hours)
