### ISSUE TITLE
 Xcode 8 beta 6: dyld: Library not loaded: @rpath/PathKit.framework/Versions/A/PathKit

### ISSUE THREAD

**Issue by shrutic** [AliSoftware/SwiftGen#161]
I am on Xcode 8 beta 6 and I have recently started getting this error. I verified that I am referencing the latest 2.0.0 version in my pod file. Could you let me know how to resolve this issue? Things that I have tried are: clean-build, delete derived data-clean-build, restart machine-clean derived data-clean-build. 

Would really appreciate your help as this is blocking me completely. 

![screen shot 2016-08-19 at 11 30 34 am](https://cloud.githubusercontent.com/assets/4141641/17820272/d9aed666-6600-11e6-9556-95a68d420c3e.png)

**Comment by AliSoftware** [comment]
Could you try to run `swiftgen` in a Terminal (outside of your Xcode build phase)?

Like just launch a terminal, `cd` to `Pods/SwiftGen/…` subdirectory and try executing `swiftgen` from the command line here. You can try just `swiftgen --version` that should be enough.
Do you have the same error when doing that?

Also, what changed between when it worked before and now that it's failing? You mentioned that "I have recently started getting this error", meaning that it worked before, so I'm wondering…

**Comment by shrutic** [comment]
I do get the exact same error(pasted at the end). I have installed Xcode 8 beta 6 5 days ago. Our team has been changing the pod file in general but nothing related to swiftgen. Today after I merged to our latest code, ran pod install, the swiftgen script that we have started failing for me. Surprisingly no one else on my team can repro this with the exact same setup which is weird. I am not sure what else I can do to debug. 

Shrutis-MacBook-Pro:bin shrutimalugu$ ./swiftgen
dyld: Library not loaded: @rpath/PathKit.framework/Versions/A/PathKit
  Referenced from: /Users/shrutimalugu/bingmd_Swift3/iOS/App/Pods/SwiftGen/bin/./swiftgen
  Reason: image not found
Trace/BPT trap: 5

**Comment by AliSoftware** [comment]
Interesting, if your coworkers don't have the issue that's probably something local and not related to an issue in `SwiftGen`'s code & install scripts itself.

I'm understanding that you install SwiftGen via Cocoapods, adding `pod 'SwiftGen'` to your project's `Podfile` (and not installing it system-wide via `homebrew` for example), right?

Maybe your last merge went wrong when merging the Pods project (I know there's sometimes some oddities with GIT + symbolic links, which framework bundles use heavily to point to `/Current` and all, maybe they went awry with last merge?)

Could you try the following, to force the reinstallation of SwiftGen on your local installation?
 - comment the `pod 'SwiftGen'` line from your Podfile
 - do a `pod install`. That will uninstall SwiftGen from your Pods
 - uncomment the `# pod 'SwiftGen'` line again
 - do a `pod install` again, to reinstall SwiftGen in your local Pods

**Comment by AliSoftware** [comment]
Any news on this? Is this only for you on your mac and not on any other machine, did you try to reinstall it properly as suggested?

**Comment by shrutic** [comment]
Sorry for delay in response. Seems like it was because my cocoapod project was out of date. I pulled in the latest cocoapod and then from command line did "brew update" , "brew upgrade swiftlint" and problem got fixed. This issue was faced by another person on our team as well

**Comment by AliSoftware** [comment]
Interesting. Will try to document that in the troubleshooting section when I have time.

Thanks a lot for the feedback!
