### ISSUE TITLE
Build fails with Xcode 7 GM

### ISSUE THREAD

**Issue by gsimmons** [AliSoftware/SwiftGen#17]
Multiple errors: 'join' is unavailable: call the 'joinWithSeparator()' method on the sequence of elements

**Comment by AliSoftware** [comment]
Are you sure you're testing the latest master? I updated all that in tag 0.4.3 (see #14) so it should be fixed.

**Comment by gsimmons** [comment]
Coulda sworn I was up to date. Sorry for the noise.
