### ISSUE TITLE
Generated files have multiple trailing newlines

### ISSUE THREAD

**Issue by ZevEisenberg** [AliSoftware/SwiftGen#170]
```
$ Pods/SwiftGen/bin/swiftgen --version
SwiftGen v3.0.0
```

Build phase:

``` sh
SWIFTGEN_BINARY="$PODS_ROOT/SwiftGen/bin/swiftgen"
SWIFTGEN_L10N_NAME="UIStrings.swift"
SWIFTGEN_IMAGES_NAME="UIImage+GeneratedAssets.swift"

SOURCE_FILES_PATH="REDACTED_APP_NAME"
SWIFTGEN_GENERATED_LOCATION="${SOURCE_FILES_PATH}/SwiftGen/Generated"
STRINGS_FILE_PATH="${SOURCE_FILES_PATH}/en.lproj/Localizable.strings"
ASSETS_PATH="${SOURCE_FILES_PATH}/Assets.xcassets"

if which ${SWIFTGEN_BINARY} >/dev/null; then
${SWIFTGEN_BINARY} strings --enumName UIStrings ${STRINGS_FILE_PATH} > ${SWIFTGEN_GENERATED_LOCATION}/${SWIFTGEN_L10N_NAME}
${SWIFTGEN_BINARY} images ${ASSETS_PATH} > ${SWIFTGEN_GENERATED_LOCATION}/${SWIFTGEN_IMAGES_NAME}
else
echo "warning: SwiftGen not installed, download from https://github.com/AliSoftware/SwiftGen"
if [[ ${CONFIGURATION} = "Debug" ]]; then
exit 0
fi
fi
```

Generated file:

``` swift
// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import Foundation

// swiftlint:disable file_length
// swiftlint:disable type_body_length
enum UIStrings {
  /// An error occurred while attempting to access this data.
  case EmptyStateGenericError
  // snip
}
// swiftlint:enable type_body_length

extension UIStrings: CustomStringConvertible {
  var description: String { return self.string }

  var string: String {
    switch self {
      case .EmptyStateGenericError:
        return UIStrings.tr("empty.state.generic.error")
        // snip
  }

  private static func tr(key: String, _ args: CVarArgType...) -> String {
    let format = NSLocalizedString(key, comment: "")
    return String(format: format, locale: NSLocale.currentLocale(), arguments: args)
  }
}

func tr(key: UIStrings) -> String {
  return key.string
}


```

Notice the multiple trailing newlines, which are triggering SwiftLint. I had hoped that the manual SwiftLint rule disabling would mean I could stop ignoring these files, but currently they still warn on the trailing newlines.

**Comment by AliSoftware** [comment]
Could you elaborate exactly where SwiftLint warns you? Is it only the trailing newline at the very end of the file or are there other warnings in these middle of the file too?

**Comment by AliSoftware** [comment]
Also does it do the same when using `--output PATH` instead of using shell indirections `> PATH`?

(Btw using `--output` is recommended is it won't touch the output file if there is no modifications, avoiding Xcode to consider the file as changed and triggering a recompilation the next time for nothing, as Xcode is based on the modification date of the files)

**Comment by ZevEisenberg** [comment]
It warns here in both the strings and images files:

![screen shot 2016-09-06 at 3 52 06 pm](https://cloud.githubusercontent.com/assets/464574/18288560/efcfbd82-7449-11e6-9562-ea7cd93a9415.png)

And it does _not_ have the same problem if you use `--output PATH`, so, I now have a great (and supported!) workaround. Thanks for the tip. Feel free to close this issue if that is satisfactory for you.
