### ISSUE TITLE
Installing using pods does not work

### ISSUE THREAD

**Issue by marcelodeaguiar** [AliSoftware/SwiftGen#173]
I have added **"pod SwiftGen"** to my pods file but after executing a pod install the folder for SwiftGen is empty and the script prints the message **SwiftGen not installed, download it from https://github...**

![screen shot 2016-09-16 at 4 41 53 pm](https://cloud.githubusercontent.com/assets/1771472/18599091/e4f041a8-7c2c-11e6-9561-6a8327697a0f.png)

![screen shot 2016-09-16 at 4 42 24 pm](https://cloud.githubusercontent.com/assets/1771472/18599092/e4f1df40-7c2c-11e6-8acb-e2def934de2d.png)

![screen shot 2016-09-16 at 4 42 38 pm](https://cloud.githubusercontent.com/assets/1771472/18599090/e4eced14-7c2c-11e6-8fb2-107269b8b55c.png)

![screen shot 2016-09-16 at 4 45 52 pm](https://cloud.githubusercontent.com/assets/1771472/18599133/22fdf576-7c2d-11e6-9398-3145296d2717.png)

**Comment by ldiqual** [comment]
@marcelodeaguiar In the build phase, remove the `which swiftgen` check and use `$PODS_ROOT/SwiftGen/bin/swiftgen strings` instead of `swiftgen strings`. It'll point to the pod binary instead of a global `swiftgen`. See https://github.com/AliSoftware/SwiftGen#installation

**Comment by moto0000** [comment]
Okey, but 'SwiftGen' folder in Pods is empty :(

**Comment by ldiqual** [comment]
@moto0000 The `SwiftGen` folder is indeed supposed to be empty when you see it in Xcode:

![image](https://cloud.githubusercontent.com/assets/941453/19787405/651bb3ea-9c57-11e6-9289-6dd7ece934aa.png)

However if you cd to it from the terminal:

```
[ldiqual@ldiqual-mbp-2 SwiftGen]$ pwd
/Users/ldiqual/Company/app/Pods/SwiftGen
[ldiqual@ldiqual-mbp-2 SwiftGen]$ ls
.            ..           CHANGELOG.md LICENSE      README.md    bin          file.zip     lib          templates
```

**Comment by phatblat** [comment]
I'm having this same issue with SwiftGen 3.0.0 installed through CocoaPods. The directory structure looks different from yours, @ldiqual and does not include the `bin` dir where the binary is expected.

```zsh
% ll Pods/SwiftGen
total 144
-rw-r--r--   1 ben  staff  19783 Nov  3 11:14 CHANGELOG.md
drwxr-xr-x   6 ben  staff    204 Nov  3 11:14 GenumKit
-rw-r--r--   1 ben  staff   1077 Nov  3 11:14 LICENSE
-rw-r--r--   1 ben  staff    574 Nov  3 11:14 Podfile
-rw-r--r--   1 ben  staff    850 Nov  3 11:14 Podfile.lock
drwxr-xr-x   9 ben  staff    306 Nov  3 11:14 Pods
-rw-r--r--   1 ben  staff  21202 Nov  3 11:14 README.md
-rw-r--r--   1 ben  staff  10684 Nov  3 11:14 Rakefile
drwxr-xr-x   6 ben  staff    204 Nov  3 11:14 SwiftGen.playground
-rw-r--r--   1 ben  staff    894 Nov  3 11:14 SwiftGen.podspec
drwxr-xr-x   5 ben  staff    170 Nov  3 11:14 SwiftGen.xcodeproj
drwxr-xr-x   4 ben  staff    136 Nov  3 11:14 SwiftGen.xcworkspace
drwxr-xr-x   8 ben  staff    272 Nov  3 11:14 UnitTests
drwxr-xr-x   4 ben  staff    136 Nov  3 11:14 documentation
drwxr-xr-x   6 ben  staff    204 Nov  3 11:14 scripts
drwxr-xr-x  10 ben  staff    340 Nov  3 11:14 swiftgen-cli
drwxr-xr-x  22 ben  staff    748 Nov  3 11:14 templates
```

**Comment by AliSoftware** [comment]
Now that SwiftGen 3.0.1 is out, can you please all check it again with this latest version?
This should be fixed now.

---

@phatblat The directory structure you got seems like the content of the root of SwiftGen's git directory. Which is strange, because the `SwiftGen.podspec` specifies that the `source` of the pod (i.e. the files CocoaPods should download to install the pod) isn't the git repo, but [the ZIP attached to the corresponding GitHub release](https://github.com/AliSoftware/SwiftGen/releases), which contains SwiftGen's pre-built binary and frameworks.

And I've just re-downloaded both the `swiftgen-3.0.0.zip` and `swiftgen-3.0.1.zip` files attached to the corresponding releases and the content of those ZIP files is as expected, containing the `bin` folder and all (and not containing the root of the Git repo as you seem to have)…

**Comment by AliSoftware** [comment]
@dostrander if you have some time to create a dummy project which uses swiftgen as a pod and check it works OK now? it would also allow us to close this issue now

**Comment by dostrander** [comment]
@phatblat could you do a `pod repo update` and then a `pod update` and check what the directory structure is again? I'm currently getting:

```
➜  TestPodProj ls -al Pods/SwiftGen
total 8152
drwxr-xr-x   9 do  staff      306 Nov  9 08:07 .
drwxr-xr-x   8 do  staff      272 Nov  9 08:07 ..
-rw-r--r--   1 do  staff    20210 Nov  9 08:07 CHANGELOG.md
-rw-r--r--   1 do  staff     1077 Nov  9 08:07 LICENSE
-rw-r--r--   1 do  staff    21202 Nov  9 08:07 README.md
drwxr-xr-x   3 do  staff      102 Nov  9 08:07 bin
-rw-r--r--   1 do  staff  4122957 Nov  9 08:07 file.zip
drwxr-xr-x  16 do  staff      544 Nov  9 08:07 lib
drwxr-xr-x  22 do  staff      748 Nov  9 08:07 templates
```

With the executable swiftgen in `bin/`. Let me know :)

**Comment by phatblat** [comment]
I'll check out 3.0.1 today!

**Comment by AliSoftware** [comment]
@phatblat ping?

**Comment by marcelodeaguiar** [comment]
@AliSoftware sorry for the delay, finally could get back to this. Installed pod 3.0.0 in this is the file structure:
![screen shot 2016-11-16 at 17 53 18](https://cloud.githubusercontent.com/assets/1771472/20363406/3ecac468-ac26-11e6-869a-672b2eec9fd0.png)

So I guess its working now. Tks.

**Comment by AliSoftware** [comment]
Cool thanks for the feedback, closing then!
