### ISSUE TITLE
"No line found in Localizable.strings" — Tilde not expanded in the path argument

### ISSUE THREAD

**Issue by AJ9** [AliSoftware/SwiftGen#18]
Tried following the example on the README:

Localizable.strings looks like this:

    "alert_title" = "Title of the alert";
    "alert_message" = "Some alert body there";
    "greetings" = "Hello, my name is %@ and I'm %d";
    "apples.count" = "You have %d apples";
    "bananas.owner" = "Those %d bananas belong to %@.";

command I run: 

    swiftgen-l10n ~./../Localizable.strings

response:

    // Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

    import Foundation

    // No line found in Localizable.strings

**Comment by AliSoftware** [comment]
Ha indeed I forgot to expand the `~` in the path. You can fix it by adding
some `stringByExpandingTildeInPath` in [swift-l10n's main.swift](
https://github.com/AliSoftware/SwiftGen/blob/master/Sources/L10n/main.swift)…
or use a path that doesn't contain ~ in the meantime

**Comment by AliSoftware** [comment]
Ha indeed I forgot to expand the `~` in the path. You can fix it by adding
some `stringByExpandingTildeInPath` in [Sources/L10n/main.swift](https://github.com/AliSoftware/SwiftGen/blob/master/Sources/L10n/main.swift) …
or use a path that doesn't contain ~ in the meantime

**Comment by AJ9** [comment]
Thanks!

**Comment by AliSoftware** [comment]
Reopening so I don't forget to add that `stringByExpandingTildeInPath` call in future versions.

**Comment by delannoyk** [comment]
Hi,

I'm also getting this issue, except that my path doesn't contain a tilde:
`swiftgen-l10n Localizable.strings`
```swift
// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import Foundation

// No line found in Localizable.strings
```

Do you have any idea what could go wrong? (I'm using brew's version (0.4.4))

**Comment by AliSoftware** [comment]
The comment may actually be a bit misleading (I should change it one day) and is generated when there would not be any "case" generated, which could happen indeed if your Localizable.strings is empty, but also if the file is not found (because you mistyped the path or the relative path was not relative to what you thought maybe?), or if the file wasn't readable at all (access rights etc), …

I should probably generate a more explicit comment (or even generate a proper error / exit code maybe) to tell whether it's a "file not found" or "error reading file" or "no problem when reading file but no string found in it" etc.

**Comment by delannoyk** [comment]
That's strange:

```bash
# swiftgen-l10n Localizable.strin
Error: The file “Localizable.strin” couldn’t be opened because there is no such file.

# ls -l
total 16
-rw-r--r--  1 kevindelannoy  staff   244 Sep 26 15:43 InfoPlist.strings
-rw-r--r--@ 1 kevindelannoy  staff  3062 Sep 30 20:30 Localizable.strings

# swiftgen-l10n Localizable.strings
// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import Foundation

// No line found in Localizable.strings
```

I also tried to type in absolute path but I have the same result.

Also, Localisable.strings just contains `"test" = "Test123";`

**Comment by AliSoftware** [comment]
Ah, very strange indeed. Is your `Localizable.strings` properly saved as a UTF-16 file, not an UTF-8 file? (as that's how Localizable.strings files are expected to be encoded by Xcode anyway)

**Comment by delannoyk** [comment]
Yup, that was encoding!

Thanks @AliSoftware :+1:

**Comment by AliSoftware** [comment]
Closing as I opened dedicated issues for the UTF8 encoding problem (#21) and the tilde not expanded (#22)
