### ISSUE TITLE
XCode 8 HomeBrew install errror

### ISSUE THREAD

**Issue by medisean** [AliSoftware/SwiftGen#180]
Error like this: You need to use Xcode 7.x to compile SwiftGen.  Use xcode-select to change the Xcode used to build from command line.

**Comment by cdzombak** [comment]
duplicates #177

**Comment by AliSoftware** [comment]
Fixed by #179.

SwiftGen 3.0.1 should be installable by Homebrew properly as soon as Homebrew/homebrew-core#6663 is merged by the Homebrew team (which shouldn't take long)!
