### ISSUE TITLE
Is this particular type of strings output possible?

### ISSUE THREAD

**Issue by Krisiacik** [AliSoftware/SwiftGen#181]
Hi..
Let's say we have a task to-do app. Here is localizable.strings file:

    "common.buttons.ok" = "OK"
    "common.buttons.cancel" = "Cancel";
    "common.buttons.retry" = "Retry";
    "common.buttons.ago" = "Ago";
    "taskList.task" = "Task";
     "taskList.date" = "date";
    "taskList.priority" = "Priority";
    "addTask.buttons.reschedule" = "Reschedule";
    "addTask.buttons.freeze" = "Freeze";

I want swiftgen to generate hierarchically organized `structs` from it:

    func localize(key: String) -> String {
        return NSLocalizedString(key, comment: "")
    }

    struct Localization {
    
        struct Common {
        
            struct Buttons {
                static var ok: String { return localize("common.buttons.ok")}
                static var cancel: String { return localize("common.buttons.cancel")}
                static var retry: String { return localize("common.buttons.retry")}
                static var ago: String { return localize("common.buttons.ago") }
            }
        }
    
        struct TaskList {
        
                static var task: String { return localize("taskList.task")}
                static var date: String { return localize("taskList.date")}
                static var priority: String { return localize("taskList.priority")}
        }
    
        struct AddTask {
            
            struct Buttons {
                static var reschedule: String { return localize("addTask.buttons.reschedule")}
                static var freeze: String { return localize("addTask.buttons.freeze") }
            }
        }
    }

This way it is very easy to reference localized strings while having the Xcode Code Completion right in the tree junctions for each more specific group which is amazing:

![localize](https://cloud.githubusercontent.com/assets/9870899/19022269/66bcd12a-8889-11e6-9763-5b5d80ee1a8d.png)

Is this currently possible?

**Comment by AliSoftware** [comment]
Yes, simply use the `structured` template to achieve this.

`swift gen strings -t structured path/to/Localizable.strings -o path/to/generated/Strings.swift`

**Comment by Krisiacik** [comment]
I tried to use 
strings-dot-syntax-swift3.stencil
strings-dot-syntax.stencil
strings-genstrings.stencil
strings-structured.stencil

it says 

    File written: /Users/Angyal/Projects/TESTPROJECTS/HW/HW/Localized.swift

But all I am ending up with is an empty file :( 

    // Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

    // No string found

**Comment by AliSoftware** [comment]
That's not related to the template but that you gave wrong or empty input when invoking the command; for example the path to your input Localizable.strings didn't exist

**Comment by Krisiacik** [comment]
I am executing this 

"swiftgen strings --templatePath /Localization/strings-structured.stencil  /Localization/Localizable.strings --output /Localization/Localized.swift"
See attached zipped folder.

I don't see anything wrong with the command line command. It simply leads to empty output.
[Localization.zip](https://github.com/AliSoftware/SwiftGen/files/509676/Localization.zip)

**Comment by AliSoftware** [comment]
If you execute this exact command, no wonder that doesn't work, as you start your path with `/` which makes them absolute paths starting from the root of your file system, and not relative path

**Comment by AliSoftware** [comment]
I just downloaded your zip file and unzipped it into my `~Downloads` folder, then opened a Terminal and switched to that folder (`cd ~/Downloads`), then run your command but by using the proper relative paths (and not the absolute paths like you did) and this works like a charm for me (SwiftGen 3.0.0)

```sh
$ cd ~/Downloads
$ ls Localization
Localizable.strings               strings-default.stencil           strings-dot-syntax.stencil        strings-structured.stencil
Localized.swift                   strings-dot-syntax-swift3.stencil strings-genstrings.stencil

$ # Check the content of the file which was present in the zip, before running the command on my Mac
$ cat Localization/Localized.swift 
// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

// No string found

$ # Running the command (with the correct relative paths — unlike in your comment)
$ swiftgen strings --templatePath Localization/strings-structured.stencil Localization/Localizable.strings --output Localization/Localized.swift
File written: Localization/Localized.swift

$ # Checking the result
$ cat Localization/Localized.swift
// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import Foundation

// swiftlint:disable file_length
// swiftlint:disable type_body_length
// swiftlint:disable nesting

enum L10n {

  case Buttons(ButtonsL10n)
  enum ButtonsL10n {
    /// OK
    case Ok
    /// Cancel
    case Cancel
    /// Retry
    case Retry
    /// Enter
    case Enter
  }
}

extension L10n: CustomStringConvertible {
  var description: String { return self.string }

  var string: String {
    switch self {
      case .Buttons(let level1key):

        switch level1key {
          case .Ok:
            return L10n.tr("buttons.ok")
          case .Cancel:
            return L10n.tr("buttons.cancel")
          case .Retry:
            return L10n.tr("buttons.retry")
          case .Enter:
            return L10n.tr("buttons.enter")
        }
    }
  }

  private static func tr(key: String, _ args: CVarArgType...) -> String {
    let format = NSLocalizedString(key, comment: "")
    return String(format: format, locale: NSLocale.currentLocale(), arguments: args)
  }
}

// swiftlint:enable type_body_length
// swiftlint:enable nesting

func tr(key: L10n) -> String {
  return key.string
}

$ # Checking the SwiftGen version
$ swiftgen --version
SwiftGen v3.0.0
```
