### ISSUE TITLE
SwiftGen 3.0.0 via Cocoapods not generate the correct style for Swift 3.0

### ISSUE THREAD

**Issue by bill350** [AliSoftware/SwiftGen#186]
When using SwiftGen 3.0.0 via Cocoapods, it seems that the swiftgen binary is the old one and generate Swift 2.2 code style.

![ScreenShot](https://cloud.githubusercontent.com/assets/2437702/19160045/cd3f12d8-8bee-11e6-9edd-13988c4b09a5.png)

Thanks

**Comment by iGranDav** [comment]
Have you added the `-t swift3` to use Swift 3 template?

**Comment by bill350** [comment]
Nope :( my fault 

So :

`$PODS_ROOT/SwiftGen/bin/swiftgen strings -t swift3 $PROJECT_DIR/MyProject...`

🍻
