### ISSUE TITLE
Localizable file not support in swift3

### ISSUE THREAD

**Issue by sarishti** [AliSoftware/SwiftGen#193]
I used the syntax as follows to create localizable for swift3 compatible
 swiftgen strings -t dot-syntax-swift3 "$PROJECT_DIR/Test/Resources/Localizable.strings" --output "$PROJECT_DIR/Test/Constants/LocalizableConstant.swift"

It is showing error in localizable constant in swift3

**Comment by toshi0383** [comment]
@sarishti I think you should provide at least error log alongside, if you report this as a bug.

**Comment by AliSoftware** [comment]
Indeed we'd need to know which errors you have exactly to understand your issue and try to solve it. Can you be more specific?

**Comment by moto0000** [comment]
add "en.lproj" to *.strings file path

**Comment by dzlobin** [comment]
I came across this yesterday, the above comment is the correct answer. The path to the Localizable.strings is `"$PROJECT_DIR/PROJECTNAME/Resources/en.lproj/Localizable.strings"`

**Comment by AliSoftware** [comment]
Closing this as it seems everyone is pointing to the rightful solution. @sarishti don't hesitate to reopen if that didn't solve your problem.
