### ISSUE TITLE
Swiftgen is always showing 0.8.0 version

### ISSUE THREAD

**Issue by jjangir610** [AliSoftware/SwiftGen#202]
I have installed 3.0 version of swiftgen in my project through pods. But when I print version using "swiftgen --version" it's still showing "SwiftGen v0.8.0". So the templates list does not contain "swift3".
So I am not able to use this awesome library with swift3.0

**Comment by jjangir610** [comment]
Resolved.. I upgraded the brew version and then reinstall swiftgen

**Comment by AliSoftware** [comment]
Yeah if you just do `swiftgen --version` from anywhere in your terminal it uses the version installed via homebrew globally on your system not the one installed via pods in YourProject/Pods/SwiftGen/bin/swiftgen :wink:
