### ISSUE TITLE
Generate accessibility identifier for XCUITests

### ISSUE THREAD

**Issue by tbaranes** [AliSoftware/SwiftGen#209]
_Just starting to play with XCUITests, so I may miss something 😬_

In order to get a label from a xib / storyboard, there's two ways:
- Set an accessibility identifier, then use `app.staticTexts["myIdentifier"]`
- Directly use `app.staticTexts["My label text"]`

I definitely prefer the first case, but it's quiet annoying to have hard coding string, or to handle manually a constant file containing all the identifiers. Since it's close of SwiftGen's goal, is that a potential feature that can fit the project?

**Comment by djbe** [comment]
I think this is a duplicate of #69?

**Comment by tbaranes** [comment]
My bad, I miss it!
