### ISSUE TITLE
[L10n] Provide a fallback for UTF8 encoding + better error messages

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/SwiftGen#21]
It seems that Xcode doesn't require anymore for your `Localizable.strings` to be UTF-16 encoded and also allows UTF8 encoded files. We should fallback to that, or use the Cocoa method that guess the encoding instead. See also #18 

It would be a good occasion to improve error messages as well.

**Comment by iGranDav** [comment]
:+1: thanks for the support

**Comment by AliSoftware** [comment]
This should be now [fixed in `master`](https://github.com/AliSoftware/SwiftGen/blob/master/GenumKit/Parsers/StringsFileParser.swift#L21) and will be available in the next release.

Don't hesitate to test the `master` branch (using `git clone` + `rake install`) even before an official version is released to confirm so I can close.

**Comment by AliSoftware** [comment]
0.6.0 fixing this has been  submitted to Homebrew rn.
