### ISSUE TITLE
outputting [comment] as part of custom strings template

### ISSUE THREAD

**Issue by simonstewart** [AliSoftware/SwiftGen#210]
I've added a new strings template, but need to output the [comment] for each of the strings to the *NSLocalizedString* call.

Ideally via something like:
{{string.comment}}

Similar to how we can use:
{{string.translation}} and {{string.key}}

Is this possible?

**Comment by djbe** [comment]
I don't think so. If you look here: [GenumKit/Parsers/StringsFileParser.swift#L38](https://github.com/AliSoftware/SwiftGen/blob/master/GenumKit/Parsers/StringsFileParser.swift#L38)
You'll see that the strings file is parsed as a dictionary of keys and translations, comments are ignored (not parsed).

**Comment by simonstewart** [comment]
@djbe that's what I found after looking through the code, but was hoping I'd misread something.

The comment is pretty NB for our translators.

**Comment by AliSoftware** [comment]
Sadly it's not easy (ready: quite complex and probably not worth it) to parse comments.
If we revert to parsing the `Localizable.strings` as a text file line by line, we'll reintroduce the bug when the translations are spread on multiple lines.
But even though, parsing comments during text parsing might proves tricky. Comments might appear anywhere in a line but we must not detect a string containing `"foo // bar"` as being a `// bar"` comment, and detecting multi-line comments would prove to be complex to parse properly without any risk of false positives (what about `/* foo /* bar // baz */ */`?)…

Maybe except if someone wrote a Swift text parser for `Localizable.strings` files that is dedicated to that and highly tested for all those side cases, in that case we could integrate that pod in our project, but if it doesn't exist yet I don't think it's worth it creating it given how complex it could become to handle all tricky cases.

**Comment by simonstewart** [comment]
@AliSoftware Appreciate the response.  

The multiline parsing will be tricky.
We'll consider patching the comment values into the XLIFF files after exporting if it becomes a deal breaker.

**Comment by djbe** [comment]
When exporting to XLIFF via Xcode, it will contain the comment information for storyboard strings (class, text and objectID).

**Comment by simonstewart** [comment]
@djbe sure, but not the calls to NSLocalizedString which is where we need the custom values.

**Comment by AliSoftware** [comment]
@simonstewart could we close this issue? as SwiftGen will not be able to parse the text file for comments (and migrating to the PLIST parsing already proved to have fixed multiple issues like multi-line translations, strings containing quotes, and more, so we're far from reverting to text parsing anyway)

We could still continue discussing to find another option fitting your specific needs.

To be honest, if you use the comments in `NSLocalizedString(…)` calls as hints to your translators so far, I'm not sure how SwiftGen could help you, as:
* if you use SwiftGen, you'll typically not have any call to `NSLocalizedString(…)` in your code anymore, but use code like `L10n.Apples.string` instead, right?
* And besides, what file do you give to your translators? I'm guessing they need the key, comment and current-value-in-some-already-used-language to translate it into another language, and all that is already present in your `.strings` file, so did you plan to provide them with the `Strings.swift` file generated by SwiftGen instead? How would that help them compared to the .strings file?
* Or maybe you wanted to create your own template to generate a different format? But in any case SwiftGen won't be able to reliably parse comments in strings file anyway :-/

Note that for this purpose (providing input to our translators) we personally use free tools like POEditor.com to fill all our translations on those kind of online platforms and let our translators have access to the texts (keys, current translation in English, comment and context) to translate on an accessible and easy to use web interface, while importing and exporting Localizable.strings for use when it's time to integrate in our app (also avoiding the risk for the translators to mess up the strings file by mistake).
Maybe that solution would better fit your needs?

**Comment by simonstewart** [comment]
@AliSoftware happy to close it, thanks.

**Comment by djbe** [comment]
Implemented by SwiftGen 6.6.0, which has been released.
