### ISSUE TITLE
[Internal] Update to Stencil 0.7.0

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/SwiftGen#216]
https://github.com/kylef/Stencil/releases/tag/0.7.0

**Comment by djbe** [comment]
The only breaking change towards users is:
> {% ifnot %} tag is now deprecated, please use {% if not %} instead.

Do we want to delay this to a major/minor version? Can we maybe provide some sort of fallback?

**Comment by kylef** [comment]
`{% ifnot %}` is deprecated, I won't be removing it until Stencil 1.0 (working towards that). I will provide a way you can "drop-in" `ifnot` into Stencil once it's been removed so you can maintain backwards compatibility of SwiftGen for custom templates.

I don't think any of the other breaking changes should be a problem, but let me know if they are.

**Comment by AliSoftware** [comment]
Cool I think we could then just drop a note in there CHANGELOG when we implement this so that people using custom template are aware of the depreciation, without having to bump to s major version just for that then :+1:

**Comment by djbe** [comment]
@kylef Saw your comment on #195, how extensive is this introspection? Can we for example process enums with associated values such as
```swift
enum Entry {
  case catalog(name: String)
  case image(name: String, value: String)
  case namespace(name: String, items: [Entry])
}
```
Just wondering what the limitations are. Always nice to have new features to simplify code! 😄

**Comment by AliSoftware** [comment]
@djbe it uses Swift reflection API `Mirror(reflecting:…)`.
I don't think this API can introspect into associated values of an enum case just yet, at least not [how is used in Stencil](https://github.com/kylef/Stencil/blob/0.7.0/Sources/Variable.swift#L91-L92).

**Comment by kylef** [comment]
That's right, I'm not sure if that would work with the current reflection APIs. If computed properties are accessible, you could perhaps provide extensions such as:

```swift
extension Entry {
  var name: String {
    switch self {
      case .catalog(let name):
        return name
      case . image(let name, _):
        return name
      case .namespace(let name, _):
        return name
    }
  }

  var value: String? {
    switch self {
      case .catalog:
        return nil
      case . image(_, let value):
        return value
      case .namespace:
        return nil
    }
  }
}
```

Not sure if that is worse than having to map each into a dictionary or not.

**Comment by kylef** [comment]
@AliSoftware @djbe As I mentioned before, I'm pushing to finish Stencil 1.0. I've finished most of the breaking API changes in Master and would love to gather any feedback.

You can see the CHANGELOG for master and the latest tag on the documentation for these changes:

- https://github.com/kylef/Stencil/blob/master/CHANGELOG.md
- https://stencil.fuller.li/en/latest/

Most notable changes is that you can no longer create a `Context` and template loaders / custom tags/filters are provided via an `Environment`. I didn't want to mix template variables and configuration (custom tags) and loaders inside the `Context` that a user provides which is the main reasons for some of these changes.

**NOTE:** *I will be further simplifying the extensions (tags/filters) API before 1.0.*

**Comment by djbe** [comment]
Cool!

I've merged the PR, so we can close this for now.
