### ISSUE TITLE
Only generate ANSI color codes if terminal supports it

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/SwiftGen#221]
Now that #204 is ready to be merged and we can run SwiftGen in Xcode directly, I've realised that we output the ANSI color codes in the output even if the terminal doesn't support it. That's especially true when testing SwiftGen directly in Xcode 8 with #204 (and Xcode 8 not supporting plugins anymore, XcodeColors isn't available in Xcode 8)

```
Usage:

    $ /Users/ohalligon/Library/Developer/Xcode/DerivedData/SwiftGen-cxsyqpzjmmxarybjxtpndqpdtviv/Build/Products/Debug/swiftgen.app/Contents/MacOS/swiftgen

Commands:

    + [32mtemplates[0m - manage custom templates
    + [32mcolors[0m - generate code for UIColors
    + [32mimages[0m - generate code for UIImages based on your Assets Catalog
    + [32mstoryboards[0m - generate code for your Storyboard scenes and segues
    + [32mstrings[0m - generate code for your Localizable.strings
    + [32mfonts[0m - generate code for your UIFonts
```

That's probably linked to Commander — which is the one generating the usage output itself — but I'm not sure if we have to do something ourselves (like detecting if we're in a non-color-capable terminal or in Xcode's console, and set a property on Commander in our Swift code to ask not to use colors, or if it should be a Commander's PR on itself to auto-detect if the terminal supports color or not.

**Comment by djbe** [comment]
Commander does it, see for example:
https://github.com/kylef/Commander/blob/master/Sources/ArgumentDescription.swift#L388

**Comment by AliSoftware** [comment]
🤔 not sure why we have them in Xcode then…

**Comment by djbe** [comment]
It just doesn't detect it, I think it just assumes the output is ANSI capable.

Meanwhile I found this:
https://github.com/onevcat/Rainbow/blob/master/Sources/OutputTarget.swift
I'll make a PR for commander to add it.

**Comment by djbe** [comment]
Jup, so Commander's tty detection isn't good enough somehow, I've tried replacing it with Rainbow's code and that works.

**Comment by AliSoftware** [comment]
:+1: perfect, thanks for investigating!

Maybe we can close this issue as it seems to be Commander's responsibility and you already opened a dedicated PR there?

**Comment by djbe** [comment]
Jup!
