### ISSUE TITLE
All leafs are complete-lowercased with dot-syntax-swift3 template

### ISSUE THREAD

**Issue by Dschee** [AliSoftware/SwiftGen#226]
When using the `dot-syntax-swift3` template and having the key

```
WORD_POOL_ITEM_FORM.NOTIFICATION.QUICK_ADD_INFO
```
the usage in code currently is:
```
L10n.WordPoolItemForm.Notification.quickaddinfo
```

As you can see the last part is not camelCased anymore. I'd expect it to be `quickAddInfo` though.

**Comment by djbe** [comment]
It works for non-uppercase keys, for:
`"WORD_POOL_ITEM_FORM.NOTIFICATION.quick_add_info" = "Something";`
I get the correct result
`L10n.WordPoolItemForm.Notification.quickAddInfo`

It goes wrong between these filters:
- `titlecase`: QUICK_ADD_INFO
- `snakeToCamelCase`: QUICKADDINFO
