### ISSUE TITLE
[SwiftLint] switch_case_on_newline warning

### ISSUE THREAD

**Issue by MickaCapi** [AliSoftware/SwiftGen#238]
First of all, thank you for this awesome tool !

I prefer to turn on the _switch_case_on_newline_ attribute on my differents projects with SwiftLint, causing multiple warnings in the generated color file.
Two solutions : 
- disable _switch_case_on_newline_ like _file_length_ and _line_length_ in each color template
- add a carriage return between the 'case:' and the returning color 

I can make a pull request to correct that.

**Comment by AliSoftware** [comment]
Indeed, makes sense to me to put the `return` in the next line after the `case:` 👍 
I'd love a PR fixing that in all affected templates 😃

**Comment by djbe** [comment]
PR has been merged.
