### ISSUE TITLE
Fix naming issues in strings dot-syntax-swift3 template

### ISSUE THREAD

**Issue by Dschee** [AliSoftware/SwiftGen#241]
Currently using the `-t dot-syntax-swift3` option leads to the following code in usage side:
```swift
L10n.Bananas.owner(p0: 2, p1: "John")
```

Instead it should be:
```swift
L10n.Bananas.owner(2, "John")
```

See https://github.com/AliSoftware/SwiftGen/pull/168#discussion_r92412861 on how this issue was introduced and where it lies. We should wait for #237 to be merged before fixing this issue though as suggested by @AliSoftware [here](https://github.com/AliSoftware/SwiftGen/pull/168#discussion_r92413697).

**Comment by AliSoftware** [comment]
:+1: but actually Swift 3 naming guidelines also states that `owner` should be lowercased in that case.

**Comment by Dschee** [comment]
Sure, good catch, just copied over from [here](https://github.com/AliSoftware/SwiftGen/pull/168#issuecomment-267022154) and forgot to update the code. Doing it now. ;)
