### ISSUE TITLE
[Colors] Support for .clr export / syncing

### ISSUE THREAD

**Issue by alladinian** [AliSoftware/SwiftGen#246]
Hi guys,

One of the major pains in Xcode development is handling colors & especially keeping track the of same colors in code <-> IB.

Swiftgen (and now code literals) solve a part of this problem, but we're still missing an easy way to use our color list in IB (I know that many of us manually create a system palette for each app and try to get it up to date with our `<colors>.txt` file).

So, what if we just added an option to create/update a `<myapp>.clr` file in the `~/Library/Colors` every time an update is triggered?

That way, we'd get a super handy (and current) list of app colors systemwide, for color pickers to choose from.

What do you think?

**Comment by AliSoftware** [comment]
I think it could be a nice idea, but not for SwiftGen imho.

The aim of SwiftGen is to generate Swift code from assets (including generating color constants from `.clr` files), not the other way around.

The best way to manage that kind of workflow imho is to synchronize your color palettes in the ~/Library directory with a local copy of the palette you keep in your git. That's the work of a tool like kicker or similar, observing file changes (like the changes in your system color palettes) and execute a custom action (like copying the updated palette in your git repo), not the work of SwiftGen which is dedicated in Swift code generation, not file syncing.

Then you can use SwiftGen to generate your Swift color constants from the clr files as usual (e.g. `swiftgen colors yourpalette.clr -o generated/colors.swift`)

**Comment by AliSoftware** [comment]
Especially why would you use a text file as input for your colors if you already have a clr file that SwiftGen can parse and use as input instead? Using the clr file as input for SwiftGen directly would remove the need to keep a text and a clr files in sync in the first place, right?

**Comment by alladinian** [comment]
Hi there (and thanx for the quick reply!)

The main issue is that, usually, designers share txt color list files that both iOS & Android parse automatically, and not clr files. 

So I thought it would be great to autogenerate a clr file, but your argument (anything else than swift generation being out of scope) makes sense, so I guess I could make a simple commandline utility and run it along in the build phases.
