### ISSUE TITLE
is swift 3 migration still pending?

### ISSUE THREAD

**Issue by kidsid-Ixigo** [AliSoftware/SwiftGen#249]
I am getting lots of compile errors in generated files for localization and storyboards on swift 3.

**Comment by djbe** [comment]
No, Swift 3 templates have been available since SwiftGen 3.0, maybe even 2.0 but I'm not sure.

Just make sure to use an up to date version, and to pass along the correct template name, such as `-t swift3`.

**Comment by kidsid-Ixigo** [comment]
Cool! thanks :-)
I was missing -t swift3 thing.
