### ISSUE TITLE
MacOS files have IOS frameworks in them

### ISSUE THREAD

**Issue by abbeyjackson** [AliSoftware/SwiftGen#259]
Hi I am using Swiftgen on a macos project and when the files are generated they are for iOS (using UIKit, etc). My runscript in my project is very basic, I am assuming there is a flag that is needed to tell Swiftgen it is for mac?

```
if which swiftgen >/dev/null; then
swiftgen storyboards "$PROJECT_DIR/DeveloperWorkLog" --output "$PROJECT_DIR/DeveloperWorkLog/Storyboards.swift"
swiftgen images "$PROJECT_DIR/DeveloperWorkLog/Assets.xcassets" --output "$PROJECT_DIR/DeveloperWorkLog/Images.swift"
fi
```

**Comment by AliSoftware** [comment]
Hello

Did you try using the templates dedicated to OSX storyboards, as described
in the dedicated part of the README?
Le dim. 15 janv. 2017 à 02:16, Abbey Jackson <notifications@github.com> a
écrit :

**Comment by abbeyjackson** [comment]
I was just coming back here to see if I could delete this. I thought I had gone through the readme again but just now noticed that bit I had not seen before. Thank you for the fast response!
