### ISSUE TITLE
Failed to generate UIImage if the shell is fish

### ISSUE THREAD

**Issue by nallwhy** [AliSoftware/SwiftGen#261]
```
sh: line 1: 77813 Abort trap: 6           /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk / -find actool 2> /dev/null
xcrun: error: unable to find utility "actool", not a developer tool or in PATH
```

**Comment by nallwhy** [comment]
Sorry, it's not certain.
But the same command works with default terminal.

**Comment by Viktoru** [comment]
I have same problem:
Xcode's output:
↳
    actool: error: unable to find utility "actool", not a developer tool or in PATH
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.
