### ISSUE TITLE
Unwanted imports storyboard generated file 

### ISSUE THREAD

**Issue by Pierre-Loup** [AliSoftware/SwiftGen#262]
Since version 4.1 the storyboard command adds an unwanted import to my generated file.
It seams to be linked to this new feature :
"Parse storyboard customModule property" #243

The viewController's `customModule` attribute doesn't update when a target is renamed.
This leads to an unwanted import.

**Comment by AliSoftware** [comment]
Thx for the issue.

This is a duplicate from #254, so I'm closing this to continue the conversation there.
