### ISSUE TITLE
[SwiftGen-Storyboard] Add support for Segues

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/SwiftGen#3]
The `SwiftGenStoryboardEnumBuilder` only build enums for Storyboards and Scenes identifiers, but not yet for Segues.

_Note: Before starting implementing it, we need to brainstorm how we want to represent that in the generated code (to structure it properly and avoid mixing in the same `enum` both some `case` for the Scene identifiers and the `cases` for the Segue identifiers)_

**Comment by esttorhe** [comment]
I was thinking in generating a different `protocol` aside from `StoryboardScene`; perhaps `StoryboardSegue` and generate the `segue`s in there.

**Comment by AliSoftware** [comment]
Yeah, I like that. But what about generated `enum`s then (I'm thinking for a nice API at the call site here)?

Would there be a `UIStoryboard.Name.Wizzard.Scene` enum for the scenes and a `UIStoryboard.Name.Wizzard.Segue` for the segues? (That starts to be ridiculously long/deep namespacing… `UIStoryboard.Name.Wizzard.Scene.CGU.viewController()` pfiew!)

Or maybe `UIStoryboard.Scenes.Wizzard` and `UIStoryboard.Segues.Wizzard` enums instead?

I'm thinking of what it would look like at the call site. So far I think something like this could be nice:

```
let vc1 = UIStoryboard.Scenes.Wizzard.CGU.viewController() // as a UIViewController
let vc2 = UIStoryboard.Scenes.Wizzard.viewController(.CGU) // same, just an alternative syntax
let vc3 = UIStoryboard.Scenes.Wizzard.passwordViewController() // typed as a XXPasswordViewController

let segue1 = UIStoryboard.Segues.Wizzard.Test.segue() // as a UIStoryboardSegue
let segue2 = UIStoryboard.Segues.Wizzard.segue(.Test) // same — alternative syntax
let segue3 = UIStoryboard.Segues.Wizzard.testSegue() // typed as a CustomStoryboardSegue
```

**Comment by esttorhe** [comment]
I think `UIStoryboard.Segue.<Name>` and `UIStoryboard.Scene.<Name>` makes the most sense to me.

I don't know if there's a need for `helper` methods to access the `segue`s other than just having the names of the available `segue` on a specific `Storyboard` though.

What do you think?

**Comment by AliSoftware** [comment]
Yeah only having an `enum` `UIStoryboard.Segue.Wizzard` with the `case Test` and `case OtherSegueName` etc, is probably enough, the `UIStoryboard.Segue.Wizzard.testSegue()` helper method are probably useless for segues as you rarely use custom subclasses for them, do you?

**Comment by esttorhe** [comment]
I rarely subclass them and even if I did there's not need to create one like that

**Comment by AliSoftware** [comment]
So to be clear, it would probably look like this, right?

```swift
extension UIStoryboard {
  enum Scene {
    /* what is currently generated in the UIStoryboard.Name enum by the current code, like: */
    enum Wizzard : String, StoryboardScene {
      static let storyboardName = "Wizzard"

      case CreateAccount = "CreateAccount"
      static var createAccountViewController : CreateAccViewController {
        return Wizzard.CreateAccount.viewController() as! CreateAccViewController
      }
      ...
    }
    enum Message : String, StoryboardScene {
      ...
    }
  }

  enum Segue {
    enum Wizzard : String, StoryboardSegue {
      case Segue1OfTheWizzardStoryboard
      case Segue1OfTheWizzardStoryboard
    }
    enum Message : String, StoryboardSegue {
      case Segue1OfTheMessageStoryboard
    }
  }
}
```

---

If so, I actually wonder what the `protocol StoryboardSegue` would contain? Maybe only a `static func segue(identifier: Self)` to build an `UIStoryboardSegue` instance from that enum, but even for that I wonder if that's even necessary, do you really instantiate `UIStoryboardSegue` instances in real life? You generally only `switch` on their identifier in `prepareForSegue()` but not much create them yourself, so…

**Comment by esttorhe** [comment]
Yeah; I don't think that's `segue(identifier:` is needed.

Exactly; I usually only need to check the segue id on the `prepareForSegue()`

**Comment by AliSoftware** [comment]
Ok great! So I'd say forget about that `StoryboardSegue` protocol for now ;)

**Comment by AliSoftware** [comment]
```
override func prepareForSegue(_ segue: UIStoryboardSegue, sender sender: AnyObject?) {
  switch UIStoryboard.Segue.Wizzard(rawValue: segue.identifier)! {
    case .Segue1OfTheWizzardStoryboard
      …
    case .Segue2OfTheWizzardStoryboard
      …
  }
}
```

That looks nice from the call site :)
