### ISSUE TITLE
Storyboard without Storyboard ID does not extend StoryboardScene

### ISSUE THREAD

**Issue by jakecraige** [AliSoftware/SwiftGen#36]
When a storyboard does not have any IDs for it's scenes you cannot use the `initialViewController` method from `StoryboardScene` because the enum doesn't extend it.

It generates code like:

```swift
extension UIStoryboard {
    struct Scene {
        enum Main {
            static let storyboardName = "Main"
        }
    }
}
```
I've toyed around with manually trying to get it to work and have been unsuccessful. Because of the `RawRepresentable` requirement on the `StoryboardScene` protocol you can't have this enum use it since there are no cases.

**Comment by AliSoftware** [comment]
Ha, good catch.

Maybe we can provide the `func storyboard()` and `func initialViewController()` default implementations in an unbound `extension StoryboardScene`, and use the `extension StoryboardScene where Self.RawValue == String` only for `func viewController()` and `static func viewController()`?

**Comment by AliSoftware** [comment]
Now that #24 is fixed and that SwiftGen now uses [templates](https://github.com/AliSoftware/SwiftGen/blob/master/templates/storyboards.stencil#L15-L30), it should be very easy to make a PR to fix this!

**Comment by jakecraige** [comment]
Awesome! Thanks for fixing this.
