### ISSUE TITLE
Return UINavigationController when applicable

### ISSUE THREAD

**Issue by gsimmons** [AliSoftware/SwiftGen#40]
It would be very helpful if the return type for any UINavigationControllers was UINavigationController instead of UIViewController.

**Comment by AliSoftware** [comment]
Agreed.

I this this will be fixed once #24 is merged, via [this](https://github.com/AliSoftware/SwiftGen/compare/stencil#diff-3ab63a4eeb740a8043e824cdc7291390R100): now I use the XML tag and prepend `UI` to it, so when the XML tag in the XIB is `<navigationController …>` or `<tableViewController …>` I'll generate `UINavigationController` or `UITableViewController`.

Would need to retest once this PR for #24 is finished and merged.

**Comment by AliSoftware** [comment]
Now that #24 is merged, this is now fixed in `master`, and [Unit Tests now ensure it stays fixed](https://github.com/AliSoftware/SwiftGen/blob/master/UnitTests/expected/Storyboards-Message-Defaults.swift.out#L41-L49).
