### ISSUE TITLE
Brew install issue

### ISSUE THREAD

**Issue by andreyslyusar** [AliSoftware/SwiftGen#46]
While installing I get next error:
```
$ brew install swiftgen 
Error: No available formula for swiftgen
Searching formulae...
Searching taps...
```

**Comment by AliSoftware** [comment]
You simply need to run `brew update` first so that Homebrew retrieve the latest formulae of Homebrew first.

See also [Homebrew documentation](https://github.com/Homebrew/homebrew#troubleshooting)

**Comment by AliSoftware** [comment]
Note: I just fixed the README to add this to the instructions.

**Comment by andreyslyusar** [comment]
Thanks a lot.
