### ISSUE TITLE
Generated UIStoryboard extension is not compiled if there are storyboard identifiers matching view controller class names

### ISSUE THREAD

**Issue by vkaramov** [AliSoftware/SwiftGen#48]
I have a few storyboards in my project. In all of them, storyboard identifiers match view controller names, for example I have  "MyViewController" identifier and MyViewController class.

**Comment by AliSoftware** [comment]
That's strange, I thought Swift was able to make the distinction between `case MyViewController` (as it should be used as `.MyViewController` at call site) and `class MyViewController`, given it should have everything needed at compile time to distinguish when you intend to reference the class and when you intend to reference the enum case.

I'd say you should maybe file a radar about that if that's indeed the case.

In the meantime, I'd be glad to have a PR to merge your commit fixing this.
