### ISSUE TITLE
Assets Improvement: Make separate enums for image folders

### ISSUE THREAD

**Issue by gsimmons** [AliSoftware/SwiftGen#52]
Like the Storyboard generator, it would be nice to have separate enums for icon folders. i.e., if I have all my main view icons in a MainViewIcons folder, it would be nice to reference them like so:
UIImage.Asset.MainViewIcons.Apple.image

**Comment by AliSoftware** [comment]
The only difficulty here is if people have multiple levels of folders, like if the user have some images at the top level, then some folders at top level, containing both images and subfolders, containing both images and subfolders, etc.

Stencil doesn't have a `{% while %}` node yet that would allow to do a template that can manage that arbitrary depth. But in the meantime, we could at least handle only one level of folders, which is probably the most common case.

**Comment by gsimmons** [comment]
I think handling one level would be quite reasonable. Thanks!

**Comment by ChristopherRogers** [comment]
I also would like to note that this is needed to fix an issue where the incorrect image name string is generated if you use the "provides namespace" option on a folder. ("properties.provides-namespace" in the Contents.json file)

**Comment by AliSoftware** [comment]
Wow I didn't even know that option existed @ChristopherRogers, TIL, thx!
Will indeed have to take that into account!

**Comment by woloda375** [comment]
+ 1

**Comment by mgorbach** [comment]
Also a great idea, and it is very similar to https://github.com/AliSoftware/SwiftGen/issues/93. I've got some work going on that, and once that's merged, the ideas and possibly the code should be able to be reused to do this, as well.

**Comment by Dimentar** [comment]
+1

**Comment by djbe** [comment]
This has been fixed, should be released really soon (in 4.1.0).
