### ISSUE TITLE
[SwiftGen-L10n] Manage positional placeholders (like `%2$@`)

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/SwiftGen#6]
As in some languages the various texts are not always in the same order, it's not that rare to have positional placeholders like `%2$@` in the `Localizable.strings` strings representing formats.

We need to be able to handle them properly, by storing the associated type at the right position in the `[PlaceholderType]` array.

Also check the official rules used by `printf` for that (like what about `%3$@ %2$f %@`, does the last `%@` use the parameter at index 3 because it's incrementing the position from the last positional character encountered (2+1)? or do it use the first parameter? What are the official rules already?)

**Comment by NachoSoto** [comment]
If I understand this correctly, it should be possible to have the same parameter multiple times, right?
For example:
```
Text: %1%@; %1%@.
```

Right now that generates a function with **two** parameters, but I would expect only one. Can you confirm that's a bug? If so I'll file a separate issue :)

**Comment by AliSoftware** [comment]
I'd also expect the resulting enum to have only one parameter in such a situation indeed! Good catch

**Comment by AliSoftware** [comment]
Wait the printf-std syntax is actually `%1$@` not `%1%@`. I thought that was an error when copying your example into the issue but in fact maybe that's why you get that result?

**Comment by NachoSoto** [comment]
Yup, I got the syntax wrong! My bad.

**Comment by AliSoftware** [comment]
Well to be fair this syntax is a little RegEx-like and confusing ^^ what an ugly standard/convention in the first place, thank you C legacy ^^
