### ISSUE TITLE
`Use of undeclared type...` when VC identifier == VC class name

### ISSUE THREAD

**Issue by ldiqual** [AliSoftware/SwiftGen#72]
I have a view controller named `DeveloperVC` in my storyboard, with class name == identifier.

![image](https://cloud.githubusercontent.com/assets/941453/11773548/64d18b7a-a1e0-11e5-989b-22b8b8afcd6b.png)

Turns out that the generated code errors out with `Use of undeclared type DeveloperVC` because the enum key is the same as the output type:

```
case DeveloperVC = "DeveloperVC"
static func developerVCViewController() -> DeveloperVC {
    return Main.DeveloperVC.viewController() as! DeveloperVC
}
```

Can't really think of a proper solution to this bug, other than renaming the VC identifier to something else. Am I missing something else?

**Comment by AliSoftware** [comment]
Is it by any chance related to #48?

In any case I think it can be considered a swift compiler bug: I think this shouldn't be ambiguous and cause problem for the compiler, even if it has the same name I don't see a use case in Swift where the `Main.DeveloperVC` case could be confused with `DeveloperVC` class as the context will always be different and shouldn't cause ambiguity for the compiler. So you might want to file a bug in bugs.swift.org :wink:

As for a workaround in the meantime, try to update to the latest release and regenerate the code and tell me if it helps as latest commits solved #48 so should hopefully solve this one too.

**Comment by AliSoftware** [comment]
Especially try to use the alternate template introduced in 0.7.0 ([see CHANGELOG here](https://github.com/AliSoftware/SwiftGen/blob/master/CHANGELOG.md#fixes-3)) dedicated to workaround this issue.

Would be interested in the JIRA bug reference once you file it at bugs.swift.org so we can all vote up for it.

**Comment by ldiqual** [comment]
@AliSoftware Thanks for your detailed response! 

 - Filed a Swift bug report here: https://bugs.swift.org/browse/SR-229
 - Using the `lowercase` template works great, thanks for pointing this out!
 - Side note: link to the dedicated documentation for templates is broken in the changelog: https://github.com/AliSoftware/SwiftGen/blob/master/CHANGELOG.md#070 (link: https://github.com/AliSoftware/SwiftGen/blob/master/Templates.md)

Thanks again!

**Comment by AliSoftware** [comment]
Thanks for your feedback! Will fix the CHANGELOG link, and up the bug report when I get home!
