### ISSUE TITLE
Static member 'Setting' cannot be used on instance of type 'UIStoryboard.Scene.Setting'

### ISSUE THREAD

**Issue by onmyway133** [AliSoftware/SwiftGen#82]
With a `case` of the same name as the `enum`

```
enum Student : String {
    case Student = ""

    static func hello() -> String {
        return Student.Student.rawValue
    }
}
```

This will yield "Static member 'Student' cannot be used on instance of type 'Student'"

The same is for `UIStoryboard` if the storyboard name and the view controller identifier is the same (case insensitive)

```
enum Setting : String, StoryboardScene {
            static let storyboardName = "Setting"

            case Setting = "setting"
            static func settingViewController() -> SettingViewController {
                return Setting.Setting.viewController() as! SettingViewController
            }
}
```

I'm on El Capitan, Xcode 7.2, swiftgen 0.7.3 with homebrew

**Comment by AliSoftware** [comment]
This is fixed in the default template of version `0.7.5` already.
