### ISSUE TITLE
Storyboard option generates invalid code

### ISSUE THREAD

**Issue by brandonroth** [AliSoftware/SwiftGen#85]
The storyboard command generates invalid code in Xcode 7.2 and 7.3 beta when naming the storyboard ID the same as the view controller class.  The offending generated code is 

```
struct StoryboardScene {
    enum Main : String, StoryboardSceneType {
        static let storyboardName = "Main"
        
        case ViewController = "ViewController"
        static func viewControllerViewController() -> ViewController {
            return StoryboardScene.Main.ViewController.viewController() as! ViewController
        }
    }
}
```

and the error is `use of undeclared type ViewController.

To reproduce:

1. Create a new single view application
2. in the storyboard give the view controller a storyboard id of "ViewController"
3. run the code generation tool.  
4. Add the generated code
5. Attempt to build and observe the error.

Renaming the storyboard ID to anything other an the name of the view controller class causes the problem to go away.  However it seems fairly common for folks to name the storyboard id after the class name as an easy way of remembering what the id is.

**Comment by AliSoftware** [comment]
What version of SwiftGen and especially which template are you using?

If you're using an old version of SwiftGen you can simply use the `-t lowercase` alternate template to avoid this.

In newer versions the default template has been changed anyway to prevent exactly this case already.

**Comment by AliSoftware** [comment]
Especially see [this entry in the CHANGELOG](https://github.com/AliSoftware/SwiftGen/blob/master/CHANGELOG.md#075) explaining the change.

(You can update to the latest version 0.7.5 using `brew upgrade` then `brew update swiftgen`)

**Comment by brandonroth** [comment]
Ah yes that was it, I was on 0.7.4 and brew didn't update it without some work.
