### ISSUE TITLE
NSString.localizedStringWithFormat to take stringsdict pluralization into account

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/SwiftGen#91]
Use `NSString.localizedStringWithFormat(format, args)` (instead of just `String(format:arguments:)` in the strings templates, to take `.stringsdict` pluralization into account.

See @marmelroy's [talk at dotSwift'16 here](https://www.youtube.com/watch?v=R9_jFbQsFWA&t=500).

**Comment by AliSoftware** [comment]
Actually according to the documentation, I'm not so sure that `String(format: arguments:)` doesn't do that already, so maybe there is no need to change anything after all?

**Comment by marmelroy** [comment]
Cool question...

So when you look at the implementation over at https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/String.swift:

```
    public init(format: String, arguments: [CVarArgType]) {
        self = String(format: format, locale: nil, arguments: arguments)
    }
```

whereas localizedStringWithFormat is implemented as:
``` 
    public static func localizedStringWithFormat(
        format: String, _ arguments: CVarArgType...
        ) -> String {
        return String(format: format, locale: NSLocale.currentLocale(),
                              arguments: arguments)
    }
```

According to Apple locale=nil is equivalent to locale=NSLocale.systemLocale() and: 

```Use the system locale when you don’t want any localizations. Use the current locale to format text that you display to users.```

**Comment by marmelroy** [comment]
So localizedStringWithFormat is the correct one.

**Comment by AliSoftware** [comment]
Ah! Good thinking into looking at the Swift OSS source code! Thanks for digging into it!

**Comment by AliSoftware** [comment]
Still feels non-Swifty to me to use a static func when an `init` is present…

I think I'll use `return String(format: format, locale: NSLocale.currentLocale(), arguments: arguments)` directly (so I actually use an initializer) instead of calling the static func `return String.localizedStringWithFormat(format, arguments)`… see any drawback in doing that?

**Comment by marmelroy** [comment]
I see your point... there is something quite ObjC-y about it. :smile: 

Anyway, there's zero difference between the two. Go with what looks nicer.

**Comment by djbe** [comment]
I've used pluralisation in a few projects, and used this for now:
```swift
String(format: NSLocalizedString("(%ld Ratings)", comment: "Ratings count"), data.ratingsCount)
```

It just works™. I honestly don't think SwiftGen needs to add separate cases, because the __keys__ stay the same. 

For reference, the corresponding stringsdict entry:
```xml
<dict>
	<key>NSStringLocalizedFormatKey</key>
	<string>(%#@ld_ratings@)</string>
	<key>ld_ratings</key>
	<dict>
		<key>NSStringFormatSpecTypeKey</key>
		<string>NSStringPluralRuleType</string>
		<key>NSStringFormatValueTypeKey</key>
		<string>ld</string>
		<key>zero</key>
		<string>No ratings yet</string>
		<key>one</key>
		<string>%ld Rating</string>
		<key>other</key>
		<string>%ld Ratings</string>
	</dict>
</dict>
```

PS: Yeah don't shoot me, I don't use swiftgen for strings yet 😞
