### ISSUE TITLE
Cocoapods compatibility

### ISSUE THREAD

**Issue by bill350** [AliSoftware/SwiftGen#95]
`brew` dependency is good but there is a major inconvenient : each development configurations (including Continuous Integration) have to install `brew` and the `swiftgen` package.

Please offer the possibility to integrate SwiftGen with Cocoapods, like **R.swift** does (see https://github.com/mac-cain13/R.swift/blob/master/R.swift.podspec)

It will be more simple to integrate SwiftGen and increase its adoption ;)

**Comment by valeIT** [comment]
+1

**Comment by AliSoftware** [comment]
Hey there,

I created a `podspec` that should allow you to install `0.7.6`, but before pushing it on CocoaPods, it would help a lot if one of you could test it!

Simply add it to your `Podfile` using the `:git =>` syntax (since it's not push on CocoaPods's trunk yet):

```
pod SwiftGen, :git => 'git@github.com:AliSoftware/SwiftGen.git'
```

Then after a `pod install` you should have all the binaries needed in the `Pods` folder so you should be able to invoke it via`$PODS_ROOT/SwiftGen/bin/swiftgen` in your build phases.

Please confirm it works ok so I could include it in the upcoming release v0.8.0 :wink:

**Comment by tomaskraina** [comment]
Hey @AliSoftware, I'm just trying it out. Unfortunately, running `pod install` does not install the binaries - there's no `bin` folder, only the source code. See the screenshot ;)

<img width="576" alt="screen shot 2016-03-08 at 16 10 23" src="https://cloud.githubusercontent.com/assets/198316/13605540/4dc22916-e548-11e5-8d0b-cd4ec6dee876.png">

**Comment by tomaskraina** [comment]
CocoaPods don't compile the project so it seems you need to precompile it and include it in this repo so it  CocoaPods will download the binary and just use it.

**Comment by tomaskraina** [comment]
What does install the binary correctly is this line in a Podfile:

`    pod 'SwiftGen', :podspec => 'https://raw.githubusercontent.com/AliSoftware/SwiftGen/master/SwiftGen.podspec'`

**Comment by AliSoftware** [comment]
Ah yeah, that's a side effect of using `:git => ` I didn't think about. Once the podspec will be pushed on trunk and you'll `pod 'SwiftGen', '~> x.y'` this issue won't exist, so good point on trying using `:podspec => …` like you did :+1: 

So once you tried with `:podspec`, did it work as expected (especially is the path to the binary relative to `$PODS_ROOT` ok, etc)?

**Comment by tomaskraina** [comment]
yep, everything works now ✌️

**Comment by AliSoftware** [comment]
Cool! Will push it on CocoaPods tonight then :+1:

I'll soon create a `0.8.0` too, so we'll be able to check if the update of a SwiftGen release works as expected too when doing `pod update SwiftGen` while a previous version is already present :wink:

Thanks a lot for testing

**Comment by samuel-mellert** [comment]
Sweet - seems like I picket the perfect moment for adopting SwiftGen! :thumbsup:

**Comment by AliSoftware** [comment]
The `podspec` for SwiftGen `0.7.6` has been pushed to CocoaPods trunk! :tada:

You can now simply write `pod 'SwiftGen'` in your `Podfile` and call it via `"$PODS_ROOT"/SwiftGen/bin/swiftgen` in your Build Phases!

Thanks a lot @bill350  @tomaskraina for testing this! :+1: 

---

_A future version is coming very soon (will maybe jump to `1.0.0` directly now?), only a few tests to do until it's ready for release, we'll ensure it's uploaded to CP too and see how the update goes :wink:_

**Comment by bill350** [comment]
Good to hear that ;)

Thank you @AliSoftware
