### ISSUE TITLE
Avoid force {whatever}ing

### ISSUE THREAD

**Issue by toshi0383** [AliSoftware/SwiftGen#96]
I thought it would be just safer to avoid force {whatever}ing.
Could you tell me reasons why you using ! mark everywhere ?
I'm thinking about some cases like when people accidentally forget to commit the Storyboard file.

**Comment by AliSoftware** [comment]
I'm totally for removing force-casting everywhere and replacing them with `guard let foo as? Bar else { fatalError("some descriptive message") }` instead :+1: 

PR welcome, it should be very easy to fix the templates about this :smiley:

**Comment by toshi0383** [comment]
Right, I'm on it ! 😀
