### ISSUE TITLE
is there a objC support

### ISSUE THREAD

**Issue by romk1n** [AliSoftware/SwiftGen#97]
Is there is a way to make the localization file be used by both swift and objective-c ?

Thanks.

**Comment by AliSoftware** [comment]
ObjC doesn't support enums with associated values. So you obviously wouldn't be able to use the same template.

But you can create your own Stencil template to generate whatever you want, including ObjC code if you need. 

[See here in the docs](https://github.com/AliSoftware/SwiftGen/blob/master/documentation/Templates.md)

**Comment by romk1n** [comment]
@AliSoftware yeah that's what i thought, i was wondering if it's possible to use enum as Int that way it would work. Got it Thanks!

**Comment by mr-fixit** [comment]
For future generations, the docs for making your own Stencil templates are [here](https://github.com/SwiftGen/templates/blob/master/Documentation/Creating-your-templates.md).

**Comment by AliSoftware** [comment]
Actually we're merging back the `templates` repo back into `SwiftGen/SwiftGen` so the link to the templates repo you pointed to will soon be outdated too 😂  The docs are now all grouped in the `Documentation` folder of the `SwiftGen` repo, [here](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/Creating-your-templates.md)

**Comment by djbe** [comment]
We've added new templates for obj-c support (PR #378, thx @mr-fixit!), it'll be available in SwiftGen 6.2.0.

**Comment by mr-fixit** [comment]
Since the OP asked about a template to generate code that would be used by **both** Swift and ObjC, PR #489 is more applicable than my code.

**Comment by djbe** [comment]
Right. The generated obj-c code is compatible with swift though, so if needed... 😆
